### ISSUE TITLE
Install the latest ember-template-lint and eslint

### ISSUE THREAD

**Issue by neojp** [ember-learn/ember-help-wanted#171]
## Expected Behavior
The app should use the latest versions of `ember-template-lint` of `eslint`.

## Actual Behavior
Currently the app relies on `ember-cli-template-lint`, which has been deprecated. This should be removed in favor of `ember-template-lint`.

https://github.com/ember-learn/ember-help-wanted/blob/5cd7ed6009a4ff355d237406c1ea5e929965623c/package.json#L41

The app also uses `eslint@v6`. Let's upgrade to `v7`.

## TODOs
- [ ] Remove `ember-cli-template-lint` and install `ember-template-lint`

    ```bash
    yarn remove ember-cli-template-lint
    yarn add --dev ember-template-lint
    ```

- [ ] Upgrade `eslint` and related packages

    ```bash
    yarn upgrade --latest eslint eslint-plugin-ember
    yarn add --dev eslint-plugin-node
    ```

    You will need to update `.eslintrc.js` to apply rules from `eslint-plugin-node`. For more information, you can create a new Ember app (e.g. `v3.21`) to see what `.eslintrc.js` should look like.

- [ ] Run `yarn lint:hbs` and `yarn lint:js` to find new lint errors. Suppress these errors by adding exceptions to `.template-lintrc.js` and `.eslintrc.js`. (Please see the related issue for more information.)

## Related
The [emberjs.com](https://emberjs.com/) website also has a similar issue to keep track of changes and progress. See https://github.com/ember-learn/ember-website/issues/669

**Comment by ijlee2** [comment]
Let me assign this issue to myself. The packages and scripts need more care than I originally expected.

**Comment by neojp** [comment]
I have fixed the linting in the templates, but still need to fix it in the js files. Do you have an issue for these yet?

**Comment by ijlee2** [comment]
No, I didn't create issues for fixing the linting yet. Can you go ahead and open a pull request for the template lint fixes? We can link this issue in the pull request description.

Thanks,
