### ISSUE TITLE
Componentize <FilterMenu>

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-help-wanted#174]
## Background

Through a series of refactoring, we'll Octanify this app and increase its maintainability.

## Problem

In the `index` and `issues` route templates, you will find duplicate code:

```handlebars
{{!-- app/templates/index.hbs, app/templates/issues.hbs --}}

<div class="help-wanted-links">
  {{#each this.navLinks.navLinks as |link|}}
    <LinkTo class="es-button" @route={{link.route}} @model={{link.model}} @query={{hash query=""}}>{{link.name}}</LinkTo>
  {{/each}}
</div>
```

## TODOs

- [ ] Use Ember CLI to create `<FilterMenu>` component. Copy-paste the following into the template:

    ```handlebars
    {{!-- app/components/filter-menu.hbs --}}

    <div class="help-wanted-links">
      {{#each this.filterNames as |filterName|}}
        <LinkTo
          class="es-button"
          data-test-link={{filterName}}
          @route="issues"
          @model={{filterName}}
          @query={{hash query=""}}
        >
          {{filterName}}
        </LinkTo>
      {{/each}}
    </div>
    ```

- [ ] In the backing class, define `filterNames`. It is an array of strings that includes the names of GitHub organizations that are related to Emberjs, plus RFCs:

    ```javascript
    // app/components/filter-menu.js

    filterNames = [
      'adopted-ember-addons',
      'ember-a11y',
      'ember-cli',
      'ember-data',
      'ember-engines',
      'ember-learn',
      'ember-template-lint',
      'emberjs',
      'empress',
      'typed-ember',
      'RFCs',
    ];
    ```

- [ ] Write a rendering test. It asserts that the component renders 11 `data-test-link`'s.

- [ ] Invoke the `<FilterMenu>` component in the `index` and `issues` route templates. Afterwards, remove the following:

    - `index` controller
    - `navLinks` injection in the `issues` controller
    - `nav-links` service

**Comment by ijlee2** [comment]
We'll want to merge this PR _after_ https://github.com/ember-learn/ember-help-wanted-server/issues/32 has been merged.

**Comment by neojp** [comment]
I have some code working for this, but it looks like data isn't working coming through even when using the constants from ember-learn/ember-help-wanted-server#32 (see the `issues` route screenshot).

My guess is we need to change the way the API is queried in `controllers/issues.js`, and refactor/remove `services/github-issues.js`.

## Screenshots

### `index` route

![image](https://user-images.githubusercontent.com/127994/95849991-1fe1be00-0d1e-11eb-897c-6ccb1a34ff1d.png)

### `issues` route

![image](https://user-images.githubusercontent.com/127994/95849967-18bab000-0d1e-11eb-9eb0-339dcce3b095.png)

**Comment by ijlee2** [comment]
Please see https://github.com/ember-learn/ember-help-wanted-server/issues/34 for what to do next on the server side.

**Comment by ijlee2** [comment]
I merged https://github.com/ember-learn/ember-help-wanted/pull/179, which affect this issue. Can you rebase your branch so that `@query` will appear in the route templates?

I updated what the component template should look like in the issue description.

**Comment by neojp** [comment]
Code has been committed to 43cfb28.

## Screenshot

![image](https://user-images.githubusercontent.com/127994/95957461-bf11be80-0dcd-11eb-8df7-5c1246a39d84.png)
