### ISSUE TITLE
Glimmerize <GithubLabel>

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-help-wanted#175]
## Background

Through a series of refactoring, we'll Octanify this app and increase its maintainability.

## Problem

The `<GithubLabel>` currently extends the classic Ember component. Let's update the template and backing class so that the component extends Glimmer component instead.

## TODOs

- [ ] Move `github-label.js` from `app/templates/components` to `app/components`. Also, update the `hbs` import syntax in the rendering tests for `<GithubLabel>` component and `{{label-with-emoji}}` helper.

    ```javascript
    // Before
    import hbs from 'htmlbars-inline-precompile';

    // After
    import { hbs } from 'ember-cli-htmlbars';
    ```

- [ ] Study the file `github-label.js`. Rewrite the template and backing class so that the component extends Glimmer component. Note that,

    - The component has 2 arguments: `@label` and `@backgroundColor`.
    - Rename `style` to `styleForLabel` and change the computed property to a plain getter.

- [x] Invoke the `<GithubLabel>` component in the `issues` route template using angle bracket syntax. (completed in #178)

- [ ] Split the existing rendering test for `<GithubLabel>` into two. One tests `@label`, and the other tests `@backgroundColor`.

**Comment by daretobedifferent18** [comment]
I would like to work on this.

**Comment by neojp** [comment]
@ijlee2 I have a commit ready for this, but I need #178 to land first.

**Comment by ijlee2** [comment]
#178 has been merged!

**Comment by neojp** [comment]
This should be completed with commit 3f701d8. I will go ahead and submit a PR.

## Screenshots
### `issues` route
![image](https://user-images.githubusercontent.com/127994/95943463-e8255580-0db3-11eb-8728-50da11c59f23.png)

### Tests
![image](https://user-images.githubusercontent.com/127994/95943404-b7452080-0db3-11eb-8f1c-6e319532774d.png)
