### ISSUE TITLE
Getting this tool to MVP status

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted#7]
For this to be a MVP, I think there are a few things remaining that need to be addressed:
- [x] set up a system to receive the webhook notifications (would envision this being a Heroku app in the interests of keeping things cheap / free)
- [x] [setup web hook](https://github.com/ember-learn/ember-help-wanted-webhook/issues/1) - handling issues based on a few tags for the repos we follow (see below).  This will receive the web hooks and handle appropriately.  Repo admins will setup webhooks to notify our system.  Would suggest that the code for this live in this repo as well (and be written in Node.js / Express) so that we can have everything in one place.
- [x] reworking our Ember app's data storage to use EmberFire / Firebase because we'll need a way to write some basic data (#5)
- [x] fix any broken tests to get all tests passing (#6)
- [ ] build a way to "claim" an item (by one or more people).  Might need to have this "unlock" after one week to indicate that it still needs help (#10)
- [x] setup Ember Suave (#13)
- [x] add in all Ember repos to be tracked by our web hook (https://github.com/ember-learn/ember-help-wanted-webhook/issues/9)
- [ ] get all Ember repos setup to send issue data via web hooks (https://github.com/ember-learn/ember-help-wanted-webhook/issues/10)
- [ ] write some real tests (https://github.com/ember-learn/ember-help-wanted/issues/22)

**Comment by acorncom** [comment]
Per discussions with folks at EmberConf, we might setup either a nightly job to check the various repos or web hooks to notify this tool of various new issues that get sent in.

**Comment by acorncom** [comment]
This tool is past MVP at this point, closing
